import { FAQ_DATA } from "./FAQ_MOCK_DATA";
import { SMATER_DATA } from "./SMARTER_MOCK_DATA";
import { TRU_STORY_DATA } from "./TRUSTORY-MOCK_DATA";
import { ITS_DATA } from "./ITS_MOCK_DATA";
import { AGENT_DIRECTORY_DATA } from "./AGENT_DIRECTORY_MOCK_DATA";
import { CONSUMER_BOT, AGENT_BOT } from "./BOT_SCRIPT";

export {
    FAQ_DATA,
    SMATER_DATA,
    TRU_STORY_DATA,
    ITS_DATA,
    AGENT_DIRECTORY_DATA,
    CONSUMER_BOT,
    AGENT_BOT,
};
